---
- name: Instalar ferramentas Python via pipx
  community.general.pipx:
    name: "{{ item }}"
    state: present

  loop: "{{ user_tooling_pipx_packages }}"

- name: Instalar hooks pre-commit
  ansible.builtin.command:
    cmd: pre-commit install

  args:
    chdir: "{{ workstation_repo }}"

  changed_when: false
