---
exclude: ^ansible/collections/ansible_collections/

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0

    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: local

    hooks:
      - id: ansible-lint
        name: ansible-lint

        entry: >-
          bash -c '
          export XDG_CACHE_HOME="$HOME/.cache" &&
          export ANSIBLE_HOME="$HOME/.cache/ansible" &&
          export ANSIBLE_LOCAL_TEMP="$HOME/.cache/ansible/tmp" &&
          export ANSIBLE_REMOTE_TEMP="$HOME/.cache/ansible/tmp" &&
          export ANSIBLE_CONFIG=ansible.cfg &&
          export ANSIBLE_COLLECTIONS_PATH=./collections &&
          mkdir -p "$HOME/.cache/ansible/tmp" &&
          cd ansible &&
          ansible-lint playbooks roles
          '

        language: system

        pass_filenames: false

        files: ^ansible/

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1

    hooks:
      - id: yamllint
