---
- name: Atualizar cache do apt
  apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Instalar pacotes básicos
  apt:
    name: "{{ common_packages }}"
    state: present
  become: true
