---
galaxy_info:
  role_name: user_vscode
  author: Daniel Bighelini
  description: Configure VS Code settings and extensions for development workstation
  license: MIT
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - all
