---
- name: Definir PATH VSCode Remote CLI
  ansible.builtin.set_fact:
    user_vscode_cli_path: >-
      /home/{{ ansible_user }}/.vscode-server/bin

- name: Localizar binário code
  ansible.builtin.shell: >
    set -o pipefail &&
    find "{{ user_vscode_cli_path }}"
    -type f
    -path "*/bin/remote-cli/code"
    | head -n 1

  register: user_vscode_code_binary

  changed_when: false

- name: Validar VSCode CLI encontrada
  ansible.builtin.fail:
    msg: >
      VSCode Remote CLI não encontrada.
      Abra o VSCode conectado ao WSL pelo menos uma vez antes do provisionamento.

  when: user_vscode_code_binary.stdout | trim == ""

- name: Obter extensões VSCode instaladas
  ansible.builtin.command:
    cmd: "{{ user_vscode_code_binary.stdout }} --list-extensions"

  environment:
    HOME: "/home/{{ ansible_user }}"

  register: user_vscode_installed_extensions

  changed_when: false

- name: Definir extensões VSCode ausentes
  ansible.builtin.set_fact:
    user_vscode_missing_extensions: >-
      {{
        user_vscode_extensions
        | difference(user_vscode_installed_extensions.stdout_lines)
      }}

- name: Instalar extensões VSCode ausentes
  ansible.builtin.command:
    cmd: "{{ user_vscode_code_binary.stdout }} --install-extension {{ item }}"

  environment:
    HOME: "/home/{{ ansible_user }}"

  loop: "{{ user_vscode_missing_extensions }}"

  when:
    - user_vscode_missing_extensions | length > 0

  register: user_vscode_extension_install

  changed_when: user_vscode_extension_install.rc == 0
