---
- name: Carregar variaveis da distribuicao
  ansible.builtin.include_vars:
    file: "{{ role_path }}/vars/{{ ansible_distribution }}.yml"

- name: Validar repositorio PowerShell definido
  ansible.builtin.assert:
    that:
      - system_powershell_repo is defined

- name: Instalar dependencias PowerShell
  ansible.builtin.apt:
    name:
      - wget
      - gpg
      - apt-transport-https

    state: present
    update_cache: true

- name: Criar diretorio keyrings
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Baixar chave Microsoft
  ansible.builtin.get_url:
    url: "{{ system_powershell_gpg_url }}"
    dest: /etc/apt/keyrings/microsoft.asc
    mode: '0644'

- name: Converter chave Microsoft
  ansible.builtin.shell: |
    set -o pipefail
    cat /etc/apt/keyrings/microsoft.asc | \
    gpg --dearmor | \
    tee /etc/apt/keyrings/microsoft.gpg > /dev/null

  args:
    creates: /etc/apt/keyrings/microsoft.gpg
    executable: /bin/bash

- name: Adicionar repositorio Microsoft
  ansible.builtin.apt_repository:
    repo: "{{ system_powershell_repo }}"
    state: present
    filename: microsoft-prod

- name: Instalar PowerShell
  ansible.builtin.apt:
    name: "{{ system_powershell_packages }}"
    state: present
    update_cache: true

- name: Validar PowerShell instalado
  ansible.builtin.command:
    cmd: pwsh -Version

  register: system_powershell_version
  changed_when: false

- name: Mostrar versao PowerShell
  ansible.builtin.debug:
    var: system_powershell_version.stdout
