---
- name: Carregar variaveis da distribuicao
  ansible.builtin.include_vars:
    file: "{{ role_path }}/vars/{{ ansible_distribution }}.yml"

- name: Validar URL PowerShell definida
  ansible.builtin.assert:
    that:
      - system_powershell_repo_url is defined

    fail_msg: >-
      Variaveis da distribuicao nao carregadas corretamente.

- name: Instalar dependencias PowerShell
  ansible.builtin.apt:
    name:
      - wget
      - apt-transport-https

    state: present
    update_cache: true

- name: Baixar repositorio Microsoft
  ansible.builtin.get_url:
    url: "{{ system_powershell_repo_url }}"
    dest: "{{ system_powershell_repo_package }}"
    mode: '0644'

- name: Registrar repositorio Microsoft
  ansible.builtin.apt:
    deb: "{{ system_powershell_repo_package }}"

- name: Atualizar cache apt
  ansible.builtin.apt:
    update_cache: true

- name: Instalar PowerShell
  ansible.builtin.apt:
    name: "{{ system_powershell_packages }}"
    state: present

- name: Validar PowerShell instalado
  ansible.builtin.command:
    cmd: pwsh -Version

  register: system_powershell_version
  changed_when: false

- name: Mostrar versao PowerShell
  ansible.builtin.debug:
    var: system_powershell_version.stdout
