---
# defaults file for user_dotfiles role
user_dotfiles_dotfiles:
  - src: bash/.bashrc
    dest: .bashrc
  - src: bash/.profile
    dest: .profile
  - src: bash/.bash_aliases
    dest: .bash_aliases
  - src: git/.gitconfig
    dest: .gitconfig
