---
# defaults file for system_docker role

system_docker_distribution: >-
  {{ ansible_facts['distribution'] | lower }}

system_docker_release: >-
  {{ ansible_facts['distribution_release'] }}

system_docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

system_docker_gpg_url: >-
  https://download.docker.com/linux/{{ system_docker_distribution }}/gpg

system_docker_repo_uri: >-
  https://download.docker.com/linux/{{ system_docker_distribution }}

system_docker_repo_suite: "{{ system_docker_release }}"

system_docker_repo_components:
  - stable

system_docker_repo_architectures:
  - amd64

system_docker_repo_signed_by: /etc/apt/keyrings/docker.gpg
