---
- name: Configurar system-space
  hosts: localhost
  connection: local

  vars:
    workstation_repo: "{{ ansible_facts.env.HOME }}/workspace/workstation-config"

  roles:
    - system-common
    - system-docker

- name: Configurar user-space
  hosts: localhost
  connection: local

  become: true
  become_user: "{{ ansible_user }}"

  vars:
    workstation_repo: "/home/{{ ansible_user }}/workstation-config"

  roles:
    - user-dotfiles
    - user-vscode