- name: Configurar workstation
  hosts: localhost
  connection: local

  vars:
    workstation_repo: "{{ ansible_facts.env.HOME }}/workspace/workstation-config"

  roles:
    - common
    - dotfiles
    - docker